# by default Travis uses JDK 8u31, which is much too old for Scala 2.12 (versions before 8u102 have issues - https://issues.scala-lang.org/browse/SI-9828)
dist: trusty
sudo: false

language: scala

scala:
  - 2.12.8
  - 2.13.0

jdk: oraclejdk8

script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success: sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: "BKtsWdL49PlO6zwuQms/Z2BKziNY0PAbcVtXHLAkIgOEs78d8+3lisHyYpF48sg8uXyXFJqL4SLeUD8AECwOabG/7wODxELqEdjg6YKVNVtyBpW7vQFZ/+G4WCJjz818I2ncxdhzGdnXlYIEAxTKCIEVVL7cTk1fX5lgWCWJ6rZQXpp2+hg0KuMNtzZM0dYakAig3Y6lx4xG0lqB7fX35LP12573uQWYO+iXBZRpmJ5YRvgFm6vkvLv6NW0lbEVfQjFoKmfIkQFD1B4Ao/cf+ee8DuwppGtR+qbvgyR7DMl6yZX26UJJ3XInMi+cGzfCIIrNIW5oTb9y5VBkxbbJEHQmrw31QkDzBwDPgqzMjKLQSsE9jbENLkDaQ02ue966xo7fTsQWLGx2+8PBWyXAjR9mziPFgoLHoiNe5rHkbUBxJ5P5VSpWVcZ4V03vaIHJ/9nNass4tmqXLEuLRQ+ZZOe6n6SDutJrrOn+xVCA2opVYhv2GQyjnhNbWy/CsCO9m7NXpf7jasq2uZUC+OcEWHQ/b7D0ikDESPjjGENYC8hQ1VdYBwofp7UQCDrKDy1xvaQa6lHTqtjAhA/UW906QabpftkOxG6/wDplUJONxY9aSGr3BOgOvCetRemApWB/hcTbyhihlz+D0XgzL6juay59mH2aX+8Q/7/T4lJNXQc="

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete